export const points = [
    {
        id: 'kremlin',
        title: 'Московский Кремль',
        address: 'Красная площадь, Москва',
        coords: [55.752023, 37.617499],
        image: '../../../../public/images/kremlin.jpg',
        rating: 4.8,
        description: 'Главная достопримечательность России.',
        type: 'Исторический объект',
    },
    {
        id: 'vdnh',
        title: 'ВДНХ',
        address: 'Проспект Мира, 119, Москва',
        coords: [55.829998, 37.633305],
        image: '../../../../public/images/vdnh.jpg',
        rating: 4.6,
        description: 'Выставочный комплекс и парк.',
        type: 'Парк и выставка',
    },
    {
        id: 'msu',
        title: 'МГУ им. Ломоносова',
        address: 'Ленинские Горы, 1, Москва',
        coords: [55.703118, 37.530887],
        image: '../../../../public/images/msu.jpg',
        rating: 4.9,
        description: 'Один из лучших университетов России.',
        type: 'Образование',
    },
    {
        id: 'ostankino',
        title: 'Останкинская башня',
        address: 'ул. Академика Королёва, 15, Москва',
        coords: [55.819543, 37.611619],
        image: '../../../../public/images/ostankino.jpg',
        rating: 4.7,
        description: 'Телевизионная башня и смотровая площадка.',
        type: 'Башня',
    },
    {
        id: 'zaryadye',
        title: 'Парк Зарядье',
        address: 'ул. Варварка, 6, стр. 1, Москва',
        coords: [55.751739, 37.630802],
        image: '../../../../public/images/zaryadye.jpg',
        rating: 4.5,
        description: 'Современный парк с панорамным видом.',
        type: 'Парк',
    },
];
